apiVersion: v2
name: Todo
description: Umbrella chart for Todo App (backend + frontend)
type: application
version: 0.0.8
appVersion: 0.0.8

dependencies:
  - name: backend
    version: 0.0.8
    repository: "file://backend"
  - name: frontend
    version: 0.0.8
    repository: "file://frontend"
