apiVersion: v2
name: backend
description: A Helm chart for Go Todo Application
type: application
# image tag possible
version: 0.0.8

# Chart version
appVersion: 0.0.8

dependencies:
  - name: postgresql
    version: "15.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
