service:
  enabled: true
  type: ClusterIP
  port: 8080
  listenPort: 8080

postgresql:
  enabled: true
  auth:
    postgresPassword: "changeme"
    username: "todoapp"
    password: "todoapp"
    database: "todoapp"
  primary:
    persistence:
      enabled: true
      size: 1Gi

ingress:
  enabled: true
  className: traefik
  #host: todo-backend.zone.internal
  # serviceName: py-backend
  tls:
    - secretName: todo-backend-tls
      hosts:
        - todo-backend.todo.svc.cluster.local
  annotations:
    kubernetes.io/ingress.className: traefik
    cert-manager.io/cluster-issuer: local-ca
    external-dns.alpha.kubernetes.io/hostname: todo-backend.zone.internal
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"

image:
  repository: foxmuldercp/go-todo-backend
  tag: latest
resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

securityContext:
  enabled: true
  data:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

# If no Prometheus is installed, set this to false due to absent ServiceMonitor CRDs
# If Prometheus is installed, set this to true and update release name
metrics:
  enabled: true
  release: kps #we should know this for service monitoring discovery

# If no NetworkPolicy is installed, set this to false. Flannel doesn't support NetworkPolicy
# If NetworkPolicy is installed via non Flannel CNI, you can use this to secure the cluster
networkPolicy:
  enabled: true
